// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoITOsUh8xKYywZD4D0dKBhxJ9OV1OwA',
    appId: '1:722362319568:web:aabfe0a0a64350d80214d5',
    messagingSenderId: '722362319568',
    projectId: 'e-commerce-cf6a3',
    authDomain: 'e-commerce-cf6a3.firebaseapp.com',
    storageBucket: 'e-commerce-cf6a3.firebasestorage.app',
    measurementId: 'G-0BYB8VTZ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-YHttOwEDc8_-zc05HHyEDqpnJQM04Q',
    appId: '1:722362319568:android:9c62a692703229fd0214d5',
    messagingSenderId: '722362319568',
    projectId: 'e-commerce-cf6a3',
    storageBucket: 'e-commerce-cf6a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUe3NxkimYjLiMwLHLeouJxZq8yE2Gd4',
    appId: '1:722362319568:ios:329353036a41b5ff0214d5',
    messagingSenderId: '722362319568',
    projectId: 'e-commerce-cf6a3',
    storageBucket: 'e-commerce-cf6a3.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUe3NxkimYjLiMwLHLeouJxZq8yE2Gd4',
    appId: '1:722362319568:ios:329353036a41b5ff0214d5',
    messagingSenderId: '722362319568',
    projectId: 'e-commerce-cf6a3',
    storageBucket: 'e-commerce-cf6a3.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5_0KKhLMJNeT1i2OQ2P1glXPyKKoZvI4',
    appId: '1:722362319568:web:28fc3c7e5128c2670214d5',
    messagingSenderId: '722362319568',
    projectId: 'e-commerce-cf6a3',
    authDomain: 'e-commerce-cf6a3.firebaseapp.com',
    storageBucket: 'e-commerce-cf6a3.firebasestorage.app',
    measurementId: 'G-YXDYCR0ZC8',
  );
}
